apiVersion: habitat.sh/v1beta1
kind: Habitat
metadata:
  name: national-parks-db
spec:
  image: habitat/np-mongodb
  count: 1
  service:
    name: np-mongodb
    topology: standalone
    group: default
---
apiVersion: habitat.sh/v1beta1
kind: Habitat
metadata:
  name: national-parks-app
spec:
  image: habitat/national-parks
  count: 1
  service:
    name: national-parks
    topology: standalone
    bind:
      - name: database
        service: np-mongodb
        group: default
---
apiVersion: v1
kind: Service
metadata:
  name: national-parks
spec:
  selector:
    habitat-name: national-parks-app
  type: NodePort
  ports:
  - name: web
    nodePort: 30001
    port: 8080
    protocol: TCP
