apiVersion: habitat.sh/v1beta1
kind: Habitat
metadata:
  name: example-v1beta1-habitat
# this field could also be left out
customVersion: v1beta1
spec:
  # the core/redis habitat service packaged as a Docker image
  image: habitat/redis-hab
  count: 1
  service:
    name: redis
    topology: standalone
    # if not present, defaults to "default"
    group: foobar
